// Generated by CoffeeScript 1.11.1
var should, user;

should = require('should');

user = require('../src/user.coffee');

describe('my first test list', function() {
  return it('should get a user w/ right parameters', function(done) {
    return user.get("jeremy", function(res) {
      res.should.equal("jeremy");
      return done();
    });
  });
});
