// Generated by CoffeeScript 1.11.1
var express, router, user;

user = require("../user");

express = require("express");

router = express.Router();

router.post('/signup', function(req, res) {
  return user.save(req.body.username, req.body.password, req.body.name, req.body.email, function(err, value) {
    if (err) {
      return res.redirect('/signup');
    } else {
      return res.redirect("/hello/" + req.body.username);
    }
  });
});

router.get('/signup', function(req, res) {
  return res.render('signup');
});

router.get('/login', function(req, res) {
  return res.render('login');
});

router.post('/login', function(req, res) {
  return user.get(req.body.username, function(err, data) {
    if (err) {
      res.redirect('/login');
    }
    if (data.pwd !== req.body.password) {
      return res.redirect('/login');
    } else if (!data.username) {
      return res.redirect('/login');
    } else {
      req.session.loggedIn = true;
      req.session.username = data.username;
      return res.redirect("/hello/" + req.body.username);
    }
  });
});

router.get('/logging', function(req, res) {
  return res.render('logging');
});

router.get('/logout', function(req, res) {
  req.session.loggedIn = false;
  delete req.session.username;
  delete req.session.count;
  delete req.session.history;
  return res.redirect('/login');
});

module.exports = router;
