// Generated by CoffeeScript 1.11.1
var LevelStore, app, bodyparser, db, express, fs, http, levelup, levelws, met, metrics, morgan, session, stream, url, user;

http = require('http');

user = require('./user');

url = require('url');

fs = require('fs');

express = require('express');

levelup = require('levelup');

levelws = require('level-ws');

bodyparser = require('body-parser');

metrics = require('./metrics');

morgan = require('morgan');

db = levelws(levelup(__dirname + "/../db/user"));

stream = db.createReadStream();

stream = db.createWriteStream();

session = require('express-session');

LevelStore = require('level-session-store')(session);

app = express();

app.set('port', 1337);

app.listen(app.get('port'), function() {});

console.log("server listening on " + (app.get('port')));

met = [
  {
    timestamp: (new Date('2013-11-04 14:00 UTC')).getTime(),
    value: 12,
    timestamp: (new Date('2013-11-04 14:10 UTC')).getTime(),
    value: 13
  }
];

metrics.save(0, met, function(err) {
  if (err) {
    throw err;
  }
  return console.log('Metrics saved');
});

app.set('views', __dirname + "/../views");

app.set('view engine', 'pug');

app.get('/', function(req, res) {
  return res.render('index', {});
});

app.use('/', express["static"](__dirname + "/../views/public"));

app.use(bodyparser.json());

app.use(bodyparser.urlencoded());

app.get('/metrics.json', function(req, res) {
  return metrics.get(function(err, data) {
    if (err) {
      throw next(err);
    }
    return res.status(200).json(data);
  });
});

db.put('key1', 'value1');

app.get('/get/:num', function(req, res) {
  res.setHeader('Content-Type', 'text/plain');
  return db.get(req.params.num, function(err, value) {
    return res.end('value:' + value);
  });
});

db.put('key 1', 'value 1');

db.put('key 2', 'value 2');

db.get('key1', function(err, value) {
  if (err) {
    return handleError(err);
  } else {
    return console.log('value:', value);
  }
});

db.del('key 2');

app.listen(1337, '127.0.0.1', function() {
  return console.log("running on 127.0.0.1:1337");
});
