// Generated by CoffeeScript 1.11.1
var app, bodyparser, db, express, fs, http, levelup, levelws, metrics, url, user;

http = require('http');

user = require('./user');

url = require('url');

fs = require('fs');

express = require('express');

levelup = require('levelup');

levelws = require('level-ws');

bodyparser = require('body-parser');

metrics = require('./metrics');

db = levelws(levelup(__dirname + "/../db"));

app = express();

app.set('port', 1337);

app.listen(app.get('port'), function() {});

console.log("server listening on " + (app.get('port')));

app.set('views', __dirname + "/../views");

app.set('view engine', 'pug');

app.get('/', function(req, res) {
  return res.render('index', {});
});

app.use('/', express["static"](__dirname + "/../views/public"));

app.use(bodyparser.json());

app.use(bodyparser.urlencoded());

app.get('/metrics.json', function(req, res) {
  return metrics.get(function(err, data) {
    if (err) {
      throw next(err);
    }
    return res.status(200).json(data);
  });
});

db.put('key 1', 'value 1');

db.put('key 2', 'value 2');

db.get('key 1', function(err, value) {
  if (err) {
    return handleError(err);
  } else {
    return console.log('value:', value);
  }
});

app.listen(1337, '127.0.0.1', function() {
  return console.log("running on 127.0.0.1:1337");
});
