// Generated by CoffeeScript 1.11.1
var db;

db = require('./db')(__dirname + "/../db/metrics");

module.exports = {
  get: function(callback) {
    return callback(null, [
      {
        timestamp: (new Date('2013-11-14 14:00 UTC')).getTime(),
        value: 1
      }
    ], [
      {
        timestamp: (new Date('2013-11-04 14:30 UTC')).getTime(),
        value: 2
      }
    ]);
  },
  post: function(callback) {},
  save: function(id, metrics, callback) {
    var i, len, metric, timestamp, value, ws;
    ws = db.createWriteStream();
    ws.on('error', callback);
    ws.on('close', callback);
    for (i = 0, len = metrics.length; i < len; i++) {
      metric = metrics[i];
      timestamp = metric.timestamp, value = metric.value;
      ws.write({
        key: "metric:" + id + ":" + timestamp,
        value: value
      });
    }
    return ws.end();
  }
};
