// Generated by CoffeeScript 1.11.1
module.exports = {
  get: function(callback) {
    return callback(null, [
      {
        timestamp: (new Date('2013-11-04 14:00 UTC')).getTime(),
        value: 12
      }, {
        timestamp: (new Date('2013-11-04 14:30 UTC')).getTime(),
        value: 15
      }
    ]);
  }
};
